#!/bin/bash
apt-get update -y

apt-get install \
    apt-transport-https \
    ca-certificates \
    curl \
    software-properties-common -y

curl -fsSL https://download.docker.com/linux/ubuntu/gpg | apt-key add -

add-apt-repository \
   "deb [arch=amd64] https://download.docker.com/linux/ubuntu \
   $(lsb_release -cs) \
   stable" -y
apt-get update -y
apt-get install docker-ce -y

docker run -d --name wlsadmin --hostname wlsadmin -p 7001:7001 -e ADMIN_PASSWORD=welcome1 iad.ocir.io/gse00015053/devop/weblogic:12213-domain
